jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        - choco install strawberryperl
      # install:
      #   - cpanm --installdeps .
      script:
        - perl -v
        - dir C:\\Strawberry\\perl\\bin
        - cpanm --version
