jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        - choco install strawberryperl
        - refreshenv
      # install:
      #   - cpanm --installdeps .
      script:
        - perl -v
        - C:\\Strawberry\\perl\\bin\\cpanm --version
        - cpanm --version
