jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        - choco install strawberryperl
        - PATH C:\\Strawberry\\perl\\bin;%PATH%
      # install:
      #   - cpanm --installdeps .
      script:
        - perl -v
        - cpanm --version
