os: windows
language: shell
perl:
  - "5.28"
  - "5.26"
env:
  # https://chocolatey.org/packages/StrawberryPerl#versionhistory
  - PERL_VERSION: 5.28.1.1
  - PERL_VERSION: 5.26.3.1
  - PERL_VERSION: 5.24.4.1
before_install:
  - env
  - cinst -y strawberryperl --version $TRAVIS_PERL_VERSION
  - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
  - perl -v
install:
  - cpanm --notest --installdeps .
script:
  - perl Makefile.PL
  - gmake
  - gmake test
