jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        - choco install strawberryperl
        - powershell
      # install:
      #   - cpanm --installdeps .
      script:
        - path
        - perl -v
        - cpanm --version
