jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        - cinst strawberryperl
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
      # install:
      #   - cpanm --installdeps .
      script:
        - which cpanm
