jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        - cinst strawberryperl
        - export "PATH=/c/Strawberry/perl/bin:$PATH"
        # - PATH C:\\Strawberry\\perl\\bin;%PATH%
        # - SET "PATH=C:\Strawberry\perl\bin;%PATH%"
      # install:
      #   - cpanm --installdeps .
      script:
        - which perl
        - C:\\Strawberry\\perl\bin\\cpanm --version
        # - env
        # - echo $PATH
        # - perl -v
        - cpanm --version
