jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        # - choco install strawberryperl
        - export "PATH=/c/Strawberry/perl/bin:$PATH"
        # - set "PATH=C:\\Strawberry\\perl\\bin;%PATH%"
      # install:
      #   - cpanm --installdeps .
      script:
        - echo $PATH
        - cpanm --version
