jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        - cinst strawberryperl
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
        # - PATH C:\\Strawberry\\perl\\bin;%PATH%
        # - SET "PATH=C:\Strawberry\perl\bin;%PATH%"
      # install:
      #   - cpanm --installdeps .
      script:
        - echo $PATH
        - /c/Strawberry/bin/cpanm --version
