jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        # - choco install strawberryperl
        - set "PATH=C:\\Strawberry\\perl\\bin;%PATH%"
        - echo $PATH
      # install:
      #   - cpanm --installdeps .
      script:
        - echo $PATH
        - cpanm --version
