jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        # - cinst strawberryperl
        - export "PATH=/c/Strawberry/perl/bin:$PATH"
        # - PATH C:\\Strawberry\\perl\\bin;%PATH%
        # - SET "PATH=C:\Strawberry\perl\bin;%PATH%"
      # install:
      #   - cpanm --installdeps .
      script:
        - which perl
        - which cpanm
        - env
        - ls -l /c/Strawberry/perl/bin
        # - echo $PATH
        # - perl -v
        # - cpanm --version
