# Default "Test" stage supports a matrix of different Perl versions to install.
os: windows
language: shell
env:
  # https://chocolatey.org/packages/StrawberryPerl#versionhistory
  - PERL_VERSION: 5.28.1.1
  - PERL_VERSION: 5.26.3.1
before_install:
  - cinst -y strawberryperl --version $PERL_VERSION
  - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
install:
  - cpanm --notest --installdeps .
script:
  - perl Makefile.PL
  - gmake
  - gmake test

# Secondary stages to include, e.g. if the default "Test" stage is on Linux, and
# you want to add stages to test on Windows.
jobs:
  include:
    # No matrix support in Stages, so install latest version of Perl. Good if
    # you just want to test against the latest version of Perl. The Stage will
    # still show `PERL_VERSION=5.28.1.1`, because it inherits the first value of
    # PERL_VERSION above, even though we don't use it.
    - stage: Windows
      os: windows
      language: shell
      before_install:
        - cinst -y strawberryperl
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
      install:
        - cpanm --notest --installdeps .
      script:
        - perl Makefile.PL
        - gmake
        - gmake test

    # Matrix hack: Declare the same stage name multiple times to test multiple
    # versions. Yes this is redundant.
    # https://github.com/travis-ci/travis-ci/issues/8295
    # First instance of "stage: Strawberry" tests 5.28.1.1.
    - stage: Strawberry
      os: windows
      language: shell
      env:
      - PERL_VERSION: 5.28.1.1
      before_install:
        - cinst -y strawberryperl --version $PERL_VERSION
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
      install:
        - cpanm --notest --installdeps .
      script:
        - perl Makefile.PL
        - gmake
        - gmake test
    # Second instance of "stage: Strawberry" tests 5.26.3.1.
    - stage: Strawberry
      os: windows
      language: shell
      env:
      - PERL_VERSION: 5.26.3.1
      before_install:
        - cinst -y strawberryperl --version $PERL_VERSION
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
      install:
        - cpanm --notest --installdeps .
      script:
        - perl Makefile.PL
        - gmake
        - gmake test
