# jobs:
#   include:
#     - stage: Windows
      os: windows
      language: shell
      env:
        - PERL_VERSION: 5.28.1.1
        - PERL_VERSION: 5.26.3.1
        - PERL_VERSION: 5.24.4.1
        # - PERL_VERSION: 5.22.3.1
        # - PERL_VERSION: 5.20.3.3
        # - PERL_VERSION: 5.18.4.1
        # - PERL_VERSION: 5.16.3.20170202
        # - PERL_VERSION: 5.14.4.1
        # - PERL_VERSION: 5.12.3.20180709
        # - PERL_VERSION: 5.10.1.5
      before_install:
        - cinst -y strawberryperl --version $PERL_VERSION
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
        - perl -v
      install:
        - cpanm --notest --installdeps .
      script:
        - perl Makefile.PL
        - gmake
        - gmake test
