jobs:
  include:
    - stage: Windows
      os: windows
      language: shell
      before_install:
        - cinst -y strawberryperl
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
        - perl -v
      install:
        - cpanm --notest Class::Delegator
      script:
        - dir /c/Strawberry/perl/bin
        - which prove
        - which cpanm
